; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes="ipsccp<func-spec>,deadargelim" -force-specialization -S < %s | FileCheck %s
; RUN: opt -passes="ipsccp<func-spec>,deadargelim" -funcspec-max-iters=1 -force-specialization -S < %s | FileCheck %s
; RUN: opt -passes="ipsccp<func-spec>,deadargelim" -funcspec-max-iters=0 -force-specialization -S < %s | FileCheck %s --check-prefix=DISABLED


define internal i32 @func(ptr %0, i32 %1, ptr nocapture %2) {
; DISABLED-LABEL: @func(
; DISABLED-NEXT:    [[TMP4:%.*]] = alloca i32, align 4
; DISABLED-NEXT:    store i32 [[TMP1:%.*]], ptr [[TMP4]], align 4
; DISABLED-NEXT:    [[TMP5:%.*]] = load i32, ptr [[TMP4]], align 4
; DISABLED-NEXT:    [[TMP6:%.*]] = icmp slt i32 [[TMP5]], 1
; DISABLED-NEXT:    br i1 [[TMP6]], label [[TMP14:%.*]], label [[TMP7:%.*]]
; DISABLED:       7:
; DISABLED-NEXT:    [[TMP8:%.*]] = load i32, ptr [[TMP4]], align 4
; DISABLED-NEXT:    [[TMP9:%.*]] = sext i32 [[TMP8]] to i64
; DISABLED-NEXT:    [[TMP10:%.*]] = getelementptr inbounds i32, ptr [[TMP0:%.*]], i64 [[TMP9]]
; DISABLED-NEXT:    call void [[TMP2:%.*]](ptr [[TMP10]])
; DISABLED-NEXT:    [[TMP11:%.*]] = load i32, ptr [[TMP4]], align 4
; DISABLED-NEXT:    [[TMP12:%.*]] = add nsw i32 [[TMP11]], -1
; DISABLED-NEXT:    [[TMP13:%.*]] = call i32 @func(ptr [[TMP0]], i32 [[TMP12]], ptr [[TMP2]])
; DISABLED-NEXT:    br label [[TMP14]]
; DISABLED:       14:
; DISABLED-NEXT:    ret i32 0
;
  %4 = alloca i32, align 4
  store i32 %1, ptr %4, align 4
  %5 = load i32, ptr %4, align 4
  %6 = icmp slt i32 %5, 1
  br i1 %6, label %14, label %7

7:                                                ; preds = %3
  %8 = load i32, ptr %4, align 4
  %9 = sext i32 %8 to i64
  %10 = getelementptr inbounds i32, ptr %0, i64 %9
  call void %2(ptr %10)
  %11 = load i32, ptr %4, align 4
  %12 = add nsw i32 %11, -1
  %13 = call i32 @func(ptr %0, i32 %12, ptr %2)
  br label %14

14:                                               ; preds = %3, %7
  ret i32 0
}

define internal void @increment(ptr nocapture %0) {
; CHECK-LABEL: @increment(
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[TMP0:%.*]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = add nsw i32 [[TMP2]], 1
; CHECK-NEXT:    store i32 [[TMP3]], ptr [[TMP0]], align 4
; CHECK-NEXT:    ret void
;
; DISABLED-LABEL: @increment(
; DISABLED-NEXT:    [[TMP2:%.*]] = load i32, ptr [[TMP0:%.*]], align 4
; DISABLED-NEXT:    [[TMP3:%.*]] = add nsw i32 [[TMP2]], 1
; DISABLED-NEXT:    store i32 [[TMP3]], ptr [[TMP0]], align 4
; DISABLED-NEXT:    ret void
;
  %2 = load i32, ptr %0, align 4
  %3 = add nsw i32 %2, 1
  store i32 %3, ptr %0, align 4
  ret void
}

define internal void @decrement(ptr nocapture %0) {
; CHECK-LABEL: @decrement(
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[TMP0:%.*]], align 4
; CHECK-NEXT:    [[TMP3:%.*]] = add nsw i32 [[TMP2]], -1
; CHECK-NEXT:    store i32 [[TMP3]], ptr [[TMP0]], align 4
; CHECK-NEXT:    ret void
;
; DISABLED-LABEL: @decrement(
; DISABLED-NEXT:    [[TMP2:%.*]] = load i32, ptr [[TMP0:%.*]], align 4
; DISABLED-NEXT:    [[TMP3:%.*]] = add nsw i32 [[TMP2]], -1
; DISABLED-NEXT:    store i32 [[TMP3]], ptr [[TMP0]], align 4
; DISABLED-NEXT:    ret void
;
  %2 = load i32, ptr %0, align 4
  %3 = add nsw i32 %2, -1
  store i32 %3, ptr %0, align 4
  ret void
}

define i32 @main(ptr %0, i32 %1) {
; CHECK-LABEL: @main(
; CHECK-NEXT:    call void @func.specialized.2(ptr [[TMP0:%.*]], i32 [[TMP1:%.*]])
; CHECK-NEXT:    [[TMP3:%.*]] = call i32 @func.specialized.1(ptr [[TMP0]], i32 0)
; CHECK-NEXT:    ret i32 [[TMP3]]
;
; DISABLED-LABEL: @main(
; DISABLED-NEXT:    [[TMP3:%.*]] = call i32 @func(ptr [[TMP0:%.*]], i32 [[TMP1:%.*]], ptr nonnull @increment)
; DISABLED-NEXT:    [[TMP4:%.*]] = call i32 @func(ptr [[TMP0]], i32 0, ptr nonnull @decrement)
; DISABLED-NEXT:    ret i32 [[TMP4]]
;
  %3 = call i32 @func(ptr %0, i32 %1, ptr nonnull @increment)
  %4 = call i32 @func(ptr %0, i32 %3, ptr nonnull @decrement)
  ret i32 %4
}

; CHECK:       6:
; CHECK:       13:
; CHECK:    ret i32 0
;
;
; CHECK:       6:
; CHECK:       12:
; CHECK:    ret void
